a = input("Enter name of Employee")
model_handle = open('models.py', 'a')
model_handle.write(f"\n\n\nclass {a}(models.Model):\n")
model_handle.write(f"\nname = models.CharField(max_length=200)\n")
model_handle.write(f"\nnumber = models.IntegerField()\n")
model_handle.write(f"\nemail = models.EmailField()\n")
model_handle.write(f"\ncity = models.CharField(max_length=300, null=True)\n")
model_handle.write(f"\nstate = models.CharField(max_length=500, null=True)\n")
model_handle.write(f"\ninsta_user = models.CharField(max_length=200)\n")
model_handle.write(f"\nweight = models.FloatField()\n")
model_handle.write(f"\nheight = models.FloatField()\n")
model_handle.write(f"\nbmi = models.FloatField()\n")
model_handle.write(f"\ngender = models.CharField(max_length=50, null=True)\n")
model_handle.write(f"\ncontact = models.CharField(max_length=220)\n")
model_handle.write(f"\ntype = models.CharField(max_length=200)\n")
model_handle.write(f"\ncreated = models.DateTimeField()\n")
model_handle.write(f"\nrescheduled = models.DateTimeField(null=True, blank=True)\n")
model_handle.write(f"\ncomment = models.TextField(null=True)\n")
model_handle.write(f"\nstatus = models.CharField(max_length=300, null=True)\n")
model_handle.write(f"\nsubstatus = models.CharField(max_length=300, null=True)\n")
model_handle.write(f"\nassigned = models.CharField(max_length=300, null=True)\n")

model_handle.close()

employee_handle=open('employee.txt','a')
employee_handle.write(f'\n{a}\n')
employee_handle.close()

admin_handle=open('admin.py','a')
admin_handle.write(f"\nadmin.site.register({a})\n")
admin_handle.close()