# Generated by Django 3.1.3 on 2021-01-13 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_auto_20210113_1328'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('plan', models.CharField(blank=True, max_length=250, null=True)),
                ('smoking', models.CharField(blank=True, max_length=100, null=True)),
                ('drinking', models.CharField(blank=True, max_length=100, null=True)),
                ('start_of_plan', models.DateTimeField(blank=True, null=True)),
                ('photo_link', models.URLField(blank=True, max_length=400, null=True)),
                ('daily_diet', models.TextField(blank=True, null=True)),
                ('sports', models.CharField(blank=True, max_length=250, null=True)),
                ('supplements', models.CharField(blank=True, max_length=250, null=True)),
                ('supplements_wish', models.TextField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=120, null=True)),
                ('diet', models.CharField(blank=True, max_length=120, null=True)),
                ('previous_workout', models.TextField(blank=True, null=True)),
                ('disease', models.TextField(blank=True, null=True)),
                ('meal_prep', models.CharField(blank=True, max_length=200, null=True)),
                ('meds', models.TextField(blank=True, null=True)),
                ('equipments', models.TextField(blank=True, null=True)),
                ('injury', models.TextField(blank=True, null=True)),
                ('dietitian_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.final')),
            ],
        ),
    ]
