# Generated by Django 3.1.3 on 2021-02-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietitian', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='dietitian_assigned',
            new_name='assigned',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='drinking',
            new_name='workout',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='smoking',
            new_name='workout_time',
        ),
        migrations.RemoveField(
            model_name='information',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='information',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='information',
            name='plan',
        ),
        migrations.AddField(
            model_name='information',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='city',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='client_secret',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='contact',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='goal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='gym',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='insta_user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='payment_method',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='state',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='telegram',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
