# Generated by Django 3.1.3 on 2021-02-15 09:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietitian', '0003_auto_20210210_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='attachment',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='last_follow_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='next_follow_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='record_follow_up',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='transformation',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='transformation'),
        ),
        migrations.AlterField(
            model_name='information',
            name='back_profile',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Bimage'),
        ),
        migrations.AlterField(
            model_name='information',
            name='front_profile',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Fimage'),
        ),
        migrations.AlterField(
            model_name='information',
            name='left_profile',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Limage'),
        ),
        migrations.AlterField(
            model_name='information',
            name='right_profile',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Rimage'),
        ),
        migrations.AlterField(
            model_name='information',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
