# Generated by Django 3.1.3 on 2021-02-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietitian', '0005_auto_20210215_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='last_follow_up',
            new_name='follow_up_last',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='next_follow_up',
            new_name='follow_up_next',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='record_follow_up',
            new_name='follow_up_record',
        ),
    ]
