# Generated by Django 3.1.3 on 2021-02-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietitian', '0006_auto_20210215_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='weight_record',
            field=models.TextField(blank=True, null=True),
        ),
    ]
