# Generated by Django 3.1.3 on 2021-02-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietitian', '0008_information_type_of_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='end_of_plan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
