# Generated by Django 3.1.3 on 2021-02-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietitian', '0010_auto_20210220_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='paid_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
