# Generated by Django 3.1.3 on 2020-11-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=300, null=True)),
                ('state', models.CharField(max_length=500, null=True)),
                ('insta_user', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('bmi', models.FloatField()),
                ('gender', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=220)),
                ('type', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('rescheduled', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(null=True)),
                ('status', models.CharField(max_length=300, null=True)),
                ('substatus', models.CharField(max_length=300, null=True)),
                ('assigned', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=300, null=True)),
                ('state', models.CharField(max_length=500, null=True)),
                ('insta_user', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('bmi', models.FloatField()),
                ('gender', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=220)),
                ('type', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('rescheduled', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(null=True)),
                ('status', models.CharField(max_length=300, null=True)),
                ('substatus', models.CharField(max_length=300, null=True)),
                ('assigned', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saurabh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=300, null=True)),
                ('state', models.CharField(max_length=500, null=True)),
                ('insta_user', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('bmi', models.FloatField()),
                ('gender', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=220)),
                ('type', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('rescheduled', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(null=True)),
                ('status', models.CharField(max_length=300, null=True)),
                ('substatus', models.CharField(max_length=300, null=True)),
                ('assigned', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
