# Generated by Django 3.1.3 on 2020-11-28 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_final'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saurabh',
        ),
        migrations.DeleteModel(
            name='UserOne',
        ),
        migrations.DeleteModel(
            name='UserThree',
        ),
        migrations.DeleteModel(
            name='UserTwo',
        ),
        migrations.DeleteModel(
            name='Vikas',
        ),
    ]
