# Generated by Django 3.1.3 on 2020-12-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201128_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='final',
            name='paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='final',
            name='purchased',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
