# Generated by Django 3.1.3 on 2020-12-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
