# Generated by Django 3.1.3 on 2020-12-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201217_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='target_achieved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
