# Generated by Django 3.1.3 on 2020-12-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201218_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final',
            name='paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='final',
            name='purchased',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
