# Generated by Django 3.1.3 on 2020-12-18 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.date(2020, 12, 14), null=True),
        ),
    ]
