# Generated by Django 3.1.3 on 2020-12-18 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201218_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date_end',
            field=models.DateField(blank=True, default=datetime.date(2020, 12, 28), null=True),
        ),
    ]
