# Generated by Django 3.1.3 on 2020-12-23 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201218_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catergory', models.TextField(null=True)),
                ('questions', models.TextField(null=True)),
                ('answers', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='info',
            name='date_end',
            field=models.DateField(blank=True, default=datetime.date(2020, 12, 27), null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.date(2020, 12, 21), null=True),
        ),
    ]
