# Generated by Django 3.1.3 on 2020-12-25 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201223_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='catergory',
            new_name='category',
        ),
    ]
