# Generated by Django 3.1.3 on 2021-02-09 08:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0016_auto_20210113_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final',
            name='bmi',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='final',
            name='contact',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='final',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='final',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='final',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='final',
            name='insta_user',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='final',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='final',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='final',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='final',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='date_end',
            field=models.DateField(blank=True, default=datetime.date(2021, 2, 14), null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.date(2021, 2, 8), null=True),
        ),
        migrations.CreateModel(
            name='Improvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=150, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.TextField(blank=True, null=True)),
                ('resolved_on', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
