# Generated by Django 3.1.3 on 2021-02-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210209_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='is_dietitian',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
