# Generated by Django 3.1.3 on 2021-02-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210213_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='is_dietitian',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
