# Generated by Django 3.1.3 on 2021-02-15 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210213_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date_end',
            field=models.DateField(blank=True, default=datetime.date(2021, 2, 21), null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.date(2021, 2, 15), null=True),
        ),
    ]
