# Generated by Django 3.1.3 on 2021-02-27 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210215_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date_end',
            field=models.DateField(blank=True, default=datetime.date(2021, 2, 28), null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.date(2021, 2, 22), null=True),
        ),
    ]
