# Generated by Django 3.1.7 on 2021-03-09 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210227_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date_end',
            field=models.DateField(blank=True, default=datetime.date(2021, 3, 14), null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.date(2021, 3, 8), null=True),
        ),
    ]
