# Generated by Django 3.1.1 on 2021-03-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210309_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='incentive',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='incentive_achieved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='percentage_achieved',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
